### ISSUE TITLE
Move CI to not use conda

### ISSUE THREAD

**Issue by BSchilperoort** [WAM2layers/WAM2layers#348]
Cartopy now has wheels available on PyPI (meaning that you can just use pip to install it, no conda needed, see #345).

This means that we also don't need micromamba on the CI, and can instead use pip.

We could also decide to use [uv](https://github.com/astral-sh/uv) to speed up the CI even more. This would just mean replacing any `pip` command with `uv pip`. 
For example, `uv pip install wam2layers[dev]`.

A complete install with `pip install uv; uv pip install wam2layers[complete]` took 36 s on my system (clean venv).
After removing that venv and doing `pip install wam2layers[complete]` in a new venv, it took 54 s.

**Comment by Peter9192** [comment]
Great suggestion. 

I'm both excited about, and a bit wary of uv. Several people have expressed concerns about the attitude of the Astral developers: making core infrastructure that many open source devs have work hard on for years obsolete without involving them in any way, and monetizing their company without being transparent about their business model. Since it's not really needed at this point, I think I'd prefer to stick with plain pip for now. E.g. https://www.youtube.com/watch?v=XzW4-KEB664, https://discuss.python.org/t/uv-another-rust-tool-written-to-replace-pip/46039/7,

**Comment by BSchilperoort** [comment]
With updating the CI I can also add apple silicon runners, to ensure everything works fine on users with the new macbooks

**Comment by Peter9192** [comment]
Currently, I'm not aware of any users or, more importantly, developers with (new) macbooks. Adding it to the CI means we need to fix it if it breaks. Let's postpone that until someone has a usecase for it (and ideally is able to develop it locally).
