### ISSUE TITLE
Unhelpful error message when dimension names are inconsistent

### ISSUE THREAD

**Issue by chrisweij** [WAM2layers/WAM2layers#377]
I got an error message while running (backtracking) a case study and I got the following error message:
"ValueError: dimensions cannot change for in-place operations"

Originating from the following line in the backtrack code:
`output["e_track"][0, :] += (s_track_upper + s_track_lower)[0, :]
`
Suggesting that the dimensions are not consistent, however the dimensions of the left and right hand side were equal to each other. It turned out that the dimension names in the tagging region (lon/lat) were not consistent with those of the preprocessed data (longitude/latitude). 

It might be worthwhile to think if we can check this during the backtracking (and provide a more useful error message).

**Comment by Peter9192** [comment]
I agree some sanity checks on the input files would be helpful. We used to have "check_input" at the end of the preprocessing:

https://github.com/WAM2layers/WAM2layers/blob/c219cf7daba5f4e991d19ec2dbf34784b7fdca7c/src/wam2layers/preprocessing/era5.py#L344-L345

The corresponding code is here: https://github.com/WAM2layers/WAM2layers/blob/c219cf7daba5f4e991d19ec2dbf34784b7fdca7c/src/wam2layers/analysis/checks.py#L112

However, we stopped using this, I think it caused more problems then it solved since the requirements were not clear enough (yet). Perhaps we can work on bringing this back, and include the region mask. 

I'm wondering if we should add this add the beginning of tracking, at the end of preprocessing, both, or as a separate utility. Any opinions?

**Comment by ruudvdent** [comment]
We agreed to make this clearer. Catch error and re-raise with a better message.

**Comment by chrisweij** [comment]
Extra optional command wam2layers check_input after preprocessing which checks dimensions, config file etc.

**Comment by ruudvdent** [comment]
Do a check at the beginning of the tracking.

**Comment by ruudvdent** [comment]
@BSchilperoort , can we close per #391 ?

**Comment by BSchilperoort** [comment]
This specific issue can be closed, more general discussion is at #384
