### ISSUE TITLE
Support for ICON data pre-processing

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#417]
This week I was in a NextGEMS hackathon, where I got to work with ICON output on a healpix grid. It seems quite straightforward to calculate input data for WAM2layers; however, the workflow is a bit different from what we have used before. Here are some main takeaways:

* Data is typically stored in zarr and read via intake-xarray
* Data is stored on a healpix grid, best to process everything there and regrid at the end

What's nice about the data is that you can start developing stuff on a low zoom level, and then scale it up for production.

I will add a notebook with some exploratory steps.

**Comment by chrisweij** [comment]
Thanks Peter, very nice, I was also at the hackaton and did similar things for the IFS output. In contrast with the ICON model data it is only available at pressure levels (currently 25 levels). Since ERA5 is basically using the IFS model, it was very easy to port the code to work with the IFS data of NextGEMS (variable names are the same, etc.). I did work on provided lat-lon grid on 0.25 degrees, but I think it would be not that difficult to work with the healpix grid as well.

**Comment by ruudvdent** [comment]
As discussed this will be moved to user-examples for now.

**Comment by Peter9192** [comment]
Done!
